### ISSUE TITLE
Compiler Errors in Visual Studio 2015 due to libyuv

### ISSUE THREAD

**Issue by jleveque** [AprilAndFriends/theoraplayer#1]
I converted the VS2012 project to VS2015, and was greeted by hundreds of compiler errors. This is due to Microsoft removing the deprecated ability to apply "__declspec(align)" to functions. This is used throughout the current version of libyuv in the libtheoraplayer project.

This issue has apparently been fixed upstream in libyuv, as of revision 1374 (https://code.google.com/p/libyuv/issues/detail?id=422), so you will just need to update the libyuv source. I fixed the errors manually and was able to compile fine, so it seems this all that is necessary to make libtheoraplayer VS2015-compliant.

**Comment by kspes** [comment]
Cool! Thanks for the info, we'll update it soon :)

On Saturday, August 1, 2015, jleveque <notifications@github.com> wrote:

> I converted the VS2012 project to VS2015, and was greeted by hundreds of
> compiler errors. This is due to Microsoft removing the deprecated ability
> to apply "__declspec(align)" to functions. This is used throughout the
> current version of libyuv in the libtheoraplayer project.
>
> This issue has apparently been fixed upstream in libyuv, as of revision
> 1374 (https://code.google.com/p/libyuv/issues/detail?id=422), so you will
> just need to update the libyuv source. I fixed the errors manually and was
> able to compile fine, so it seems this all that is necessary to make
> libtheoraplayer VS2015-compliant.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AprilAndFriends/theoraplayer/issues/1>.
>


-- 
---
Krešo

**Comment by kspes** [comment]
libyuv updated, give it a try and let us know if it works for you.

https://libtheoraplayer.wordpress.com/2015/08/19/libyuv-update/

**Comment by jleveque** [comment]
Looks good. Everything compiles without errors. Thanks! You should now be able to create a proper VS2015 project for libtheoraplayer without any surprises.
