### ISSUE TITLE
audio only?

### ISSUE THREAD

**Issue by blitz-research** [AprilAndFriends/theoraplayer#28]
Hi,

Is it possible to use theoraplayer as an audio player only?

Not such a big deal if it isn't but it would save a me a day or 2 of coding!

Bye,
Mark

**Comment by kspes** [comment]
eh, I guess you can simply discard frames and get only the audio, but the CPU would still process frames and spend resources doing it.
We could add a flag to the video clip to have it not decode the video stream, but that might not work on MP4 or WebM, not sure.

also, why would you need this anyway?
In your use case, you can just keep the audio file separate and use it to do a/v sync for video playback, and when you need audio only, just pipe it through your audio api?

**Comment by blitz-research** [comment]
Nah never mind, I don't want video being decoded while I stream music!

I was just thinking that since I'm already using theoraplayer for in game videos, it'd be nice if I could also use it for background music etc, instead of writing my own threaded vorbis decoder etc from scratch. 

But that's just crazy talk I guess!

**Comment by blloyd75** [comment]
Perhaps use the vorbis decoder like theora player does?  It's not a hard interface.

Brian A Lloyd

**Comment by borisblizzard** [comment]
We actually have an audio solution that we internally rather than theoraplayer's implementation. You might find it useful since it's also multiplatform.
https://github.com/AprilAndFriends/xal
