### ISSUE TITLE
Crash if audio gain < 1.0f

### ISSUE THREAD

**Issue by d1ke** [AprilAndFriends/theoraplayer#3]
First of all thank your for great library!

When i set audio gain, my application crashes inside your library.
Seems that problem is here:
```C++
void TheoraAudioPacketQueue::addAudioPacket(float** buffer, int numSamples, float gain)
{
    ...
    if (gain < 1.0f)
    {
        ...
        *dataptr = buffer[i][j] * gain;
    }
    else
    {
        ...
        *dataptr = buffer[j][i];
    }
}
```

Note different order of i and j.  
Also i think it would be safer to compare gain with 1.0f - FLT_EPSILON or 1.0f - std::numeric_limits<float>::epsilon().

**Comment by kspes** [comment]
Thanks, glad you like the lib :)

Loool what a stupid bug, the i and j are inverted if gain is applied. Fixed!
